// title: Interfaces
= Interfaces - xref:../index.adoc[Home]

* <<interfaces---home,Interfaces - Home>>
 ** <<in-a-nutshell,In a nutshell>>
 ** <<the-problem,The problem>>
 ** <<what-is-an-interface,What is an interface?>>
 ** <<implementing-an-interface,Implementing an interface>>
 ** <<fixing-the-original-problem,Fixing the original problem>>
 ** <<dependency-injection,Dependency injection>>
 ** <<when-to-use-interfaces,When to use interfaces>>
 ** <<where-to-go-from-here,Where to go from here>>

== In a nutshell

Interfaces let you say what you want your code to do without specifying how it does it.

== The problem

Imagine a program that lets people register accounts and edit their username.

[source,csharp]
----
public void ChangeUsername(int userID, string newName)
{
    var user = new UserDetailsDatabaseLoader.Load(id);
    user.Name = newName;
}
----

We use `DatabaseLoader`, which we've made elsewhere in our program, to get the user's details from a database. How `DatabaseLoader` works doesn't matter. What matters is that it does something useful for us.

Now imagine that instead of loading information from a database, you want to get it from the filesystem. You have to:

* Create a new service that gets information from the filesystem.
* Change every part of your program that used `DatabaseLoader` to now use `FilesystemLoader`.

[source,csharp]
----
public void ChangeUsername(int userID, string newName)
{
    var user = new FilesystemLoader.Load(id);
    user.Name = newName;
}
----

Changing your program like this isn't too annoying when you only have to change one line. But imagine that  you have to move lots of code over to the new `FilesystemLoader`. Now imagine that you realise you need to get user information from https://en.wikipedia.org/wiki/Homing_pigeon[carrier pigeons] instead.

[source,csharp]
----
public void ChangeUsername(int userID, string newName)
{
    var user = CarrierPigeonLoader.Load(id);
    user.Name = newName;
}
----

All of these `Loader` classes have done the same thing - get user information. They did this in different ways, but in our `ChangeUsername` method, we don't care about how the service got the information - we just want the information.

We need a way to express what we want out code to do (get a user's details) without specifying how it's done (database, filesystem, carrier pigeon). This means we wouldn't need to update `ChangeUsername` if we come up with another way of completing this task.

This is what interfaces do.

== What is an interface?

An interface is a list of method signatures. Read the explanation on xref:delegates.adoc[delegates] for an explanation of method signatures.

Here is an interface with one method signature, named `Load`.

[source,csharp]
----
interface ILoader
{
    User Load(int id);
}
----

An interface looks similar to a class, with two differences:

* You use the `interface` keyword.
* You only define method signatures. You cannot define fields or method bodies in an interface.

____
💡 You can actually define https://www.infoq.com/articles/default-interface-methods-cs8/[interface method bodies] from C# 8.0 onwards. You should not do this until you understand why the feature is available.
____

== Implementing an interface

By themselves, interfaces don't do anything. Interfaces are not 'real' classes -- not something concrete you  actually use. You can't create an instance of an interface with the `new` keyword.

Interfaces exist so actual classes can 'implement' them. When a class implements an interface, it says 'I promise to have methods that match those in the interface'.

[source,csharp]
----
// The syntax for implementing an interface is identical to inheriting from a class.
class CarrierPigeonLoader : ILoader
{
    // Without this method, your program will no longer compile.
    public User Load(int id)
    {
        // catch the bird, read the message on its leg...
    }
}
----

`ILoader` defined a method called 'Load' that takes an `int` and returns a `User`.
Because `CarrierPigeonLoader` implements `ILoader`, it has to have a method that matches that signature.

== Fixing the original problem

Imagine that you modified `DatabaseLoader`, `FilesystemLoader` and `CarrierPigeonLoader` to all implement `ILoader`.

We now know that whenever we use _any_ of those classes, they *will* have a method named 'Load' that takes an `int` and returns a `User`. They will likely do this in different ways. That's OK. All we care about is the input (our `int`) and what we get back (the `User`).

Let's modify our original method.

[source,csharp]
----
public void ChangeUsername(int userID, string newName)
{
    ILoader loader = new CarrierPigeonLoader();
    var user = loader.Load(id);
    user.Name = newName;
}
----

We can't create an instance of `ILoader` with `new`, but we can declare a variable of type `ILoader`.

When we declare a variable of an interface, it means 'I can be any of the classes that implement me'. If you are familiar with polymorphism, think of how a parent class can stand in for any class that inherits from it.

In the second line, where we call `loader.Load()`, `loader` could be any class that implements our interface.

== Dependency injection

So far, this likely seems quite pointless. We have done a lot of extra work for nothing. We've created an interface, but we still say `new CarrierPigeonLoader()` in our method. We would have to update that every time we wanted to get user information in a new way.

The magic trick which makes interfaces actually useful is xref:dependency-injection.adoc[dependency injection].

public void ChangeUsername(ILoader loader, int userID, string newName)
{
    var user = loader.Load(id);
    user.Name = newName;
}

Our method no longer has any idea what `loader` 'really' is. As a result, we wouldn't have to update this method if we created a `MorseCodeLoader` or a `SignLanguageLoader`. Whatever code that calls `ChangeUsername` can swap out different implementations of `ILoader`, and the method won't notice that anything's changed.

But this still isn't great. Now the code that calls `ChangeUsername` has to be updated instead.

It is good by itself for lower-level parts of our programs to use interfaces and higher-level parts deal with concrete types. But if we use a DI framework (as I explain in the page on xref:dependency-injection.adoc[dependency injection]), we can centralise all of our service-creation in just one place. This means we could change our implementation of `ILoader` throughout our entire program by updating a few lines of code in just one place.

== When to use interfaces

You should consider creating an interface when you need to call on another class to get something done, but you don't care how it does it.

== Where to go from here

You will end up working with interfaces a lot in .NET, if only due to LINQ. Understanding interfaces will make the question 'what is the difference between `IEnumerable<>` and `List<>`?' a lot easier to understand.
