= Dependency injection
Jack Kendall <jkendall3096@gmail.com>
:toc:
:pp: {plus}{plus}
:source-highlighter: highlightjs

xref:../index.adoc[Home]

Dependency injection is when you get something through a class's constructor rather than creating it in the class itself.

[source,csharp]
----
public class MyClass
{
 private readonly HttpClient _client;

 public MyClass(HttpClient client)
 {
    _client = client;
 }

 public void DownloadExample()
 {
    _client.DownloadAsync("www.example.com");
 }
}
----

This is dependency injection. 

Rather than creating a `HttpClient` with the 'new' keyword, you get one through the constructor.

Lots of tools and patterns have been created to make dependency injection more powerful, but it all comes down to getting stuff through a constructor.

== So what?

There are several reasons why this pattern is useful.

* `MyClass` isn't cluttered with code for creating the `HttpClient`.
* We can see everything the class needs (its 'dependencies') just by looking at its constructor.
* You can't create an instance of `MyClass` without giving it a `HttpClient`. If you did this in a separate method, outside of the constructor, you could forget to call it.

You now understand dependency injection. 

The rest of the page explains ways to make this pattern more powerful.

== Dependency injection does not reduce complexity. It just moves it around

In the example above, `MyClass` asked for a `HttpClient` in its constructor. 

When we create an instance of MyClass, it will look like this.

[source,csharp]
----
class Program
{
 public static void Main(string[] args)
 {
  // create what we need
  var client = new HttpClient();

  // pass it in
  var myClass = new MyClass(client);

  // actually do something
  myClass.DownloadExample();
 }
}
----

MyClass is simpler, but now another part of our code is more complicated.

We have to create everything somewhere, no matter how cleverly we hide it.

It would be nice if we could create _everything_ our program needs all in one place. 

That way, we could stuff it all into a method or a class and not worry about it.

We do this with a 'container'.

== Containers

A dependency injection container automates creating classes and passing them to other classes.

A container sits at the start of your program, usually in `Main`.

You 'register' classes with the container, and it will automatically figure out which classes depend on each other.

You then 'resolve' these dependencies to start using your classes and get the program running.

[source,csharp]
----
class Program
{
 public static void Main(string[] args)
 {
  // Create a container.
  var container = new ExampleDIContainer();

  // Register our classes.
  container.Register<MyClass>();
  container.Register<HttpClient>();

  // The container knows that MyClass needs a HttpClient.
  // Because we registered the HttpClient class, our container can create one.
  // The container creates a HttpClient and uses it to make a MyClass.
  var myClass = container.Resolve<MyClass>();

  // Use our classes however we like.
  myClass.DownloadExample();
 }
}
----

This is obviously a very simple example.

Imagine you had fifty classes that all depended on each other. It would be painful figuring out which to instantiate first.

A container does all of that for you. They're very good at helping programs scale without becoming difficult to work with.

DI containers all work differently, but the concept of 'registering' and 'resolving' classes is universal.

== A more interesting example

Here is an extract from a real project I wrote using DI.

It shows how you can set up lots of classes in more complicated programs.

You can https://github.com/jkendall327/QuietTime/blob/main/QuietTime/Other/DIContainerProvider.cs[find the full code here].

Don't worry if you don't understand parts of this. 

When you see methods like `AddSingleton` or `AddTransient`, those really just mean 'register this class for me'.

[source, csharp]
----
        // This method returns a complete DI container.
        // You can pass containers around like any other variable.
        public async Task<ServiceProvider> GetContainer()
        {
            var services = new ServiceCollection();

            // Omitted for brevity.
            // RegisterHostServices(services);
            // RegisterPages(services);

            return await RegisterServices(services);
        }

        private async Task<ServiceProvider> RegisterServices(ServiceCollection services)
        {
            // scheduling
            StdSchedulerFactory schedulerFactory = new();
            IScheduler scheduler = await schedulerFactory.GetScheduler();

            services.AddSingleton<ScheduleJobFactory>();
            services.AddSingleton<IScheduler>(scheduler);
            services.AddTransient<ISchedulingService, Scheduler>();

            // notifications
            services.AddSingleton<TaskbarIcon>();
            services.AddSingleton<Dispatcher>(Application.Current.Dispatcher);

            services.AddSingleton<INotifier, Notifier>();

            // audio
            services.AddTransient<MMDeviceEnumerator>();
            services.AddSingleton<IAudioLocker, AudioLocker>();

            // serialization
            services.AddTransient<ISerializer, Serializer>();

            // autostart
            services.AddTransient<Autostarter>();

            // create service provider
            return services.BuildServiceProvider();
        }
----

The process here is the same as in the basic example.

1. Create a DI container. (`var services = new ServiceCollection();`)
2. Register services.
3. Tell the container to figure out how the classes relate to each other. (`services.BuildServiceProvider()`)

== Interfaces

NOTE: Feel free to skip this section if you don't understand interfaces.

xref:../csharp/interfaces.adoc[Interfaces] are not part of dependency injection. But they work well together, so it's common to ask for an interface in a constructor.

This makes your code more flexible. In the example above, `MyClass` doesn't know where its `HttpClient` comes from. If we asked for an interface instead of a concrete class, MyClass also wouldn't know what specific class it was using.

We could give MyClass anything that implemented the interface and MyClass wouldn't know the difference. 

We can use this to easily change how our code works.

[source, csharp]
----
// An interface defines some action, like sending a notification, but not how it's done.
// This is often called a 'service', because it does something useful for other bits of code.
interface INotifier
{
    void NotifyUser(string message);
}

// 'Concrete' classes implement the interface and 'do the work' of sending notifications.
class MessageBoxNotifier : INotifier
{
    public void NotifyUser(string message)
    {
        MessageBox.Show(message);
    }
}

// You can have multiple classes that implement the interface.
// Dependency injection lets us swap between our implementations easily.
class EmailNotifier : INotifier
{
    public void NotifyUser(string message)
    {
        EmailClient.SendEmail(message);
    }
}

// If a class wants to send notifications, it asks for an interface.
// Classes that ask for services are often called 'clients'.
public class MainWindow
{
    INotifier _notificationService;

    // Ask for an interface instead of a concrete class.
    public MainWindow(INotifier notifier)
    {
        // Set it to a field so other methods can use it.
        _notificationService = notifier;
    }

    // Imagine this being called when the user clicks a button to sign up for an account.
    public void UserRegistrationButton_OnClick(object sender, EventArgs e)
    {
        // MainWindow doesn't know if this will open a messagebox or send an email.
        _notificationService.NotifyUser("Your account has been created successfully.");
    }
}

// Somewhere else, we decide what implementation to actually give to MainWindow.
public class Program
{
    public static void Main(string[] args)
    {
        // If we want to send emails instead, we can
        // change how our program functions by changing
        // this single line of code.
        INotifier notifier = new MessageBoxNotifier();

        // Give the client its implementation.
        var mainWindow = new MainWindow(notifier);
    }
}

----

This is an extremely common and extremely powerful design pattern.

It's also very common in xref:unit-testing.adoc[unit testing], because it lets you 'mock' services easily.

== The end-goal

All your classes should get their dependencies through their constructor, and all dependencies should be created in one place at the start of the program.

NOTE: You can actually use DI with xref:../csharp/properties.adoc[properties] instead of constructors. This is much less common.

You no longer have a complicated web of classes that depend on each other in confusing ways. Now your classes are more modular and lightweight.

You don't need a container, but they are convenient.

== Further reading

The best way to get confident with DI is to use it in your own projects.

Popular DI containers for .NET include https://autofac.org/[Autofac] and https://www.castleproject.org/projects/windsor/[Castle Windsor].

Microsoft also has an official container for .NET Core. You need the `Microsoft.Extensions.DependencyInjection` NuGet package to use it.

ASP.NET Core uses dependency injection by default.