= Logging
Jack Kendall <jkendall3096@gmail.com>
:toc:
:pp: {plus}{plus}
:source-highlighter: highlightjs

xref:../index.adoc[Home]

Logging is when your program sends out messages to explain what it's doing.

== Why use logging?

Programs are complicated. Design patterns and clever coding styles reduce this, but programs will always be difficult to fully understand. The gap between what we think a program does and what it actually does is the cause of almost all bugs.

Logging is a way for programs to tell us what they are doing.

This can tell us what branches of execution our program hits, or doesn't. It can record business events, like when a user makes a purchase on an online store.

Logging gives us information that helps us analyze and debug programs.

== An example

The simplest form of logging is writing messages to the console.

[source,csharp]
----
public int MyMethod(int x)
{
    Console.WriteLine("The value of the argument is: " + x);

    x = x * x;

    Console.WriteLine("The value of the argument squared is: " + x);

    return x;
}
----

This is simple to implement, but has flaws.

* It's not permanent. We lose this information when the program ends.
* It depends on having a console to write to.
* It's just flat text. There is no metadata to help us find interesting patterns in the logs.

== Solutions

For serious programs, _structured logging_ is very useful. In contrast to using `Console.WriteLine`, structured logs aren't just text. They're usually https://en.wikipedia.org/wiki/JSON[JSON], a format which lets us include metadata about the messages we're recording.

A popular way to get structured logging in C# is to use the https://serilog.net/[Serilog] library.
