= Unit testing
Jack Kendall <jkendall3096@gmail.com>
:toc:
:pp: {plus}{plus}
:source-highlighter: highlightjs

xref:../index.adoc[Home]

== In a nutshell

Unit tests are code that automatically run other bits of code. They usually check if your code has bugs, or make sure you don't accidentally break old code with new updates.

== Example

The idea of code that can tell if other code is correct or not might seem magical. Unit tests are actually very mundane. Here is what one looks like:

[source,csharp]
----
        public int ReturnsFour()
        {
            return 4;
        }

        [Fact]
        public void ReturnsFour_ShouldReturnFour()
        {
            var expected = 4;
            var actual = ReturnsFour();

            Assert.Equal(expected, actual);
        }
----

As you can see, this is incredibly complex and sensitive code - thank god we have tests to prove it works.

The second method here is the unit test. In .NET/C#, test methods usually have an attribute (the line in square brackets above the method name).

But what really makes it a unit test is the last line. All unit tests call some kind of `Assert` method that checks if two values are equal, or if a `bool` is true, or something similar. This is what determines if the unit test passes or fails.

As a result, you can write perfectly useless tests like this:

[source,csharp]
----
        [Fact]
        public void ReturnsFour_ShouldReturnFour()
        {
            var expected = 4;
            var actual = ReturnsFour();

            Assert.Equal(true, true);
        }
----

This test will always 'pass'.

In the sample above, I've tried to illustrate as many 'best practices' about unit tests as possible. I will now explain them.

=== Naming

Naming things well https://hilton.org.uk/blog/why-naming-things-is-hard[is famously difficult]. To counter this, there is a standard naming pattern for unit tests in C#.

. The name of the method you are testing.
. What the method 'should' do.
. (Optional) Under what conditions Step 2 is true.

For example, you might give a test this name: `CountUsers_ShouldReturnZero_WhenDatabaseIsEmpty`.

=== Expected and actual

Every unit test is about comparing the result of some operation with what you expect it to be.

It is a good idea to literally use the names 'expected' and 'actual' in tests to make it clear to everyone else who reads your code what your expectations are.

=== Arrange, act, assert

I didn't show this in the example because it was too short, but there is also a conventional way to order your unit tests.

First, you _arrange_ what you need to perform the test.

Then, you _act_ by performing the operation you are testing.

Finally, you _assert_ to find out if the result if what you expect.
