// title: A tour of Visual Studio
= A tour of Visual Studio - xref:../index.adoc[Home]
:pp: {plus}{plus}

* <<a-tour-of-visual-studio---home,A tour of Visual Studio - Home>>
 ** <<in-a-nutshell,In a nutshell>>
 ** <<visual-studio-versus-visual-studio-code,Visual Studio versus Visual Studio Code>>
 ** <<installing-visual-studio,Installing Visual Studio>>

== In a nutshell

Visual Studio is Microsoft's big, monolithic program for writing, compiling, debugging and compiling programs. It is easy to pick up, but it has many features and dark corners that are hard to understand.

This page will give an overview of its main features and how to use them effectively.

== Visual Studio versus Visual Studio Code

Visual Studio is entirely different from Visual Studio Code (or as it's more commonly called, VSCode).

VSCode is a lightweight text editor along the lines of Notepad{pp} or Atom. While it supports plugins that give it advanced features - like syntax highlighting or code debugging.

If you're unsure which program to use to write C#, you are probably best off with Visual Studio. It handles more things for you by default.

== Installing Visual Studio

Because Visual Studio is a large program, you can choose which parts of it to install. You may only be interested in features that let you program in C{pp}, for example, or which focus on web development.

There is a separate program, called the Visual Studio Installer, where you can choose what features to install. These features are grouped into 'workloads'.

You should make sure the .NET development workload is installed before you use Visual Studio to write C# (or any other .NET language).
