= Desktop project types
Jack Kendall <jkendall3096@gmail.com>
:toc:
:pp: {plus}{plus}
:source-highlighter: highlightjs

xref:../index.adoc[Home]

There are several ways to create .NET programs that run on desktop computers:

* Winforms is outdated and Windows-only, but simple to use
* WPF is more complicated than Winforms and Windows-only, but very powerful
* Xamarin Forms is similar to WPF that targets Windows and mobile devices
* MAUI is an evolution of Xamarin Forms that targets more platforms but isn't fully released yet
* Avalonia is like a cross-platform WPF, but it's not created by Microsoft

== Which project type should I choose?

If you are new to C# and want to move on from making console apps, Winforms is simple to work with.

If you are frustrated with Winforms' limitations or want to get familiar with one of the other desktop project types, study WPF.

Use Xamarin Forms or MAUI if you want to create mobile apps.

Use Avalonia if you want to make a WPF-style app on multiple platforms right now.

== Winforms

== WPF

The most important thing about WPF is that it introduced something called XAML, which would be used in most desktop project types from then on.

XAML is basically a form of XML that you use to describe the interface of your app.

[source,xml]
----
<Button>
    <Button.FontWeight>Bold</Button.FontWeight>
    <Button.Content>
        <WrapPanel>
            <TextBlock Foreground="Blue">Multi</TextBlock>
            <TextBlock Foreground="Red">Color</TextBlock>
            <TextBlock>Button</TextBlock>
        </WrapPanel>
    </Button.Content>
</Button>
----

(Example taken from https://wpf-tutorial.com/xaml/basic-xaml/[this very useful website].)
