// title: .NET versions
= .NET versions - xref:../index.adoc[Home]

* <<net-versions---home,.NET versions - Home>>
 ** <<in-a-nutshell,In a nutshell>>
 ** <<warning,Warning>>
 ** <<history,History>>

== In a nutshell

.NET is the general name for Microsoft's programming platform. .NET Framework, .NET Core and .NET 5 are all different 'versions' of .NET.

== Warning

This page describes the different versions of .NET. It doesn't explain what .NET 'really' is, how it's different from C#, or what the CLR is.

== History

.NET began in the late 1990s as Microsoft's response to Java.

Rather than just releasing their version of Java as a product, they decide to make it a _standard_. A standard is just a description of what a system 'should' look like -- not a concrete implementation of it you can actually use. You can find some of https://www.mono-project.com/docs/about-mono/languages/ecma/[the .NET standards here].

The first implementation of the .NET specification was .NET Framework. Its key characteristics were that it was closed-source and Windows-only.

.NET Core was the second implementation, released in 2016. It was open-source from the start and cross-platform.

In the meantime, there was also the https://www.mono-project.com/[Mono project], which reimplemented .NET framework in an open-source way. This was the entire point of making .NET a _standard_ -- anyone could come along and make their own implementation of it. .NET Core took a lot of influence from Mono.

.NET Core is very similar to .NET Framework in most ways. However, there are some differences.

This matters mostly in terms of https://www.nuget.org/[Nuget packages] -- little add-on libraries you can download to use in your projects. A Nuget package made for .NET Framework wouldn't be guaranteed to work on .NET Core.

In response, Microsoft created the very confusingly-named .NET Standard. This was a set of libraries that all official (i.e. made by Microsoft) implementations of .NET would be guaranteed to have. So if your Nuget package targeted .NET Standard, you'd know it would work pretty much anywhere.

We now have three official implementations of .NET: .NET Framework, .NET Core, .NET Standard.

Microsoft recognised that this situation was confusing, and in 2020/2021 brought in the new 'one .NET' campaign.

This meant three things:

* There would be no new work on .NET Framework, except bugfixes and security patches.
* .NET Standard would be discontinued.
* The next version of .NET Core would be named .NET 5.0.

From now on (assuming Microsoft doesn't change their minds), there will be only one official implementation of .NET, and its versions will just be named things like .NET 6, .NET 7, .NET 8, etc.

To put it clearly: .NET 5 is just .NET Core with a different name. As a result, it's also open-source and cross-platform.
